// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Property.proto

package org.thingmodel.proto;

public final class ProtoProperty {
  private ProtoProperty() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PropertyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 string_key = 1;
    /**
     * <code>required int32 string_key = 1;</code>
     */
    boolean hasStringKey();
    /**
     * <code>required int32 string_key = 1;</code>
     */
    int getStringKey();

    // required .ThingModel.Proto.Property.Type type = 2 [default = STRING];
    /**
     * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
     */
    boolean hasType();
    /**
     * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
     */
    Property.Type getType();

    // optional .ThingModel.Proto.Property.Location location_value = 3;
    /**
     * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
     */
    boolean hasLocationValue();
    /**
     * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
     */
    Property.Location getLocationValue();
    /**
     * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
     */
    Property.LocationOrBuilder getLocationValueOrBuilder();

    // optional .ThingModel.Proto.Property.String string_value = 4;
    /**
     * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
     */
    boolean hasStringValue();
    /**
     * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
     */
    Property.String getStringValue();
    /**
     * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
     */
    Property.StringOrBuilder getStringValueOrBuilder();

    // optional double double_value = 5;
    /**
     * <code>optional double double_value = 5;</code>
     */
    boolean hasDoubleValue();
    /**
     * <code>optional double double_value = 5;</code>
     */
    double getDoubleValue();

    // optional int32 int_value = 6;
    /**
     * <code>optional int32 int_value = 6;</code>
     */
    boolean hasIntValue();
    /**
     * <code>optional int32 int_value = 6;</code>
     */
    int getIntValue();

    // optional bool boolean_value = 7;
    /**
     * <code>optional bool boolean_value = 7;</code>
     */
    boolean hasBooleanValue();
    /**
     * <code>optional bool boolean_value = 7;</code>
     */
    boolean getBooleanValue();

    // optional int64 datetime_value = 8;
    /**
     * <code>optional int64 datetime_value = 8;</code>
     */
    boolean hasDatetimeValue();
    /**
     * <code>optional int64 datetime_value = 8;</code>
     */
    long getDatetimeValue();
  }
  /**
   * Protobuf type {@code ThingModel.Proto.Property}
   */
  public static final class Property extends
      com.google.protobuf.GeneratedMessage
      implements PropertyOrBuilder {
    // Use Property.newBuilder() to construct.
    private Property(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Property(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Property defaultInstance;
    public static Property getDefaultInstance() {
      return defaultInstance;
    }

    public Property getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Property(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stringKey_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              Type value = Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              Location.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = locationValue_.toBuilder();
              }
              locationValue_ = input.readMessage(Location.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(locationValue_);
                locationValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              String.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = stringValue_.toBuilder();
              }
              stringValue_ = input.readMessage(String.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stringValue_);
                stringValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              doubleValue_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              intValue_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              booleanValue_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              datetimeValue_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoProperty.internal_static_ThingModel_Proto_Property_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoProperty.internal_static_ThingModel_Proto_Property_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Property.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Property> PARSER =
        new com.google.protobuf.AbstractParser<Property>() {
      public Property parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Property(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Property> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ThingModel.Proto.Property.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOCATION_POINT = 0;</code>
       */
      LOCATION_POINT(0, 0),
      /**
       * <code>LOCATION_LATLNG = 1;</code>
       */
      LOCATION_LATLNG(1, 1),
      /**
       * <code>LOCATION_EQUATORIAL = 2;</code>
       */
      LOCATION_EQUATORIAL(2, 2),
      /**
       * <code>STRING = 3;</code>
       */
      STRING(3, 3),
      /**
       * <code>DOUBLE = 4;</code>
       */
      DOUBLE(4, 4),
      /**
       * <code>INT = 5;</code>
       */
      INT(5, 5),
      /**
       * <code>BOOLEAN = 6;</code>
       */
      BOOLEAN(6, 6),
      /**
       * <code>DATETIME = 7;</code>
       */
      DATETIME(7, 7),
      ;

      /**
       * <code>LOCATION_POINT = 0;</code>
       */
      public static final int LOCATION_POINT_VALUE = 0;
      /**
       * <code>LOCATION_LATLNG = 1;</code>
       */
      public static final int LOCATION_LATLNG_VALUE = 1;
      /**
       * <code>LOCATION_EQUATORIAL = 2;</code>
       */
      public static final int LOCATION_EQUATORIAL_VALUE = 2;
      /**
       * <code>STRING = 3;</code>
       */
      public static final int STRING_VALUE = 3;
      /**
       * <code>DOUBLE = 4;</code>
       */
      public static final int DOUBLE_VALUE = 4;
      /**
       * <code>INT = 5;</code>
       */
      public static final int INT_VALUE = 5;
      /**
       * <code>BOOLEAN = 6;</code>
       */
      public static final int BOOLEAN_VALUE = 6;
      /**
       * <code>DATETIME = 7;</code>
       */
      public static final int DATETIME_VALUE = 7;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return LOCATION_POINT;
          case 1: return LOCATION_LATLNG;
          case 2: return LOCATION_EQUATORIAL;
          case 3: return STRING;
          case 4: return DOUBLE;
          case 5: return INT;
          case 6: return BOOLEAN;
          case 7: return DATETIME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Property.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ThingModel.Proto.Property.Type)
    }

    public interface LocationOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required double x = 1 [default = 0];
      /**
       * <code>required double x = 1 [default = 0];</code>
       */
      boolean hasX();
      /**
       * <code>required double x = 1 [default = 0];</code>
       */
      double getX();

      // required double y = 2 [default = 0];
      /**
       * <code>required double y = 2 [default = 0];</code>
       */
      boolean hasY();
      /**
       * <code>required double y = 2 [default = 0];</code>
       */
      double getY();

      // optional double z = 3 [default = 0];
      /**
       * <code>optional double z = 3 [default = 0];</code>
       */
      boolean hasZ();
      /**
       * <code>optional double z = 3 [default = 0];</code>
       */
      double getZ();

      // optional int32 string_system = 4;
      /**
       * <code>optional int32 string_system = 4;</code>
       *
       * <pre>
       * WGS84 by default
       * </pre>
       */
      boolean hasStringSystem();
      /**
       * <code>optional int32 string_system = 4;</code>
       *
       * <pre>
       * WGS84 by default
       * </pre>
       */
      int getStringSystem();

      // optional bool z_null = 5 [default = false];
      /**
       * <code>optional bool z_null = 5 [default = false];</code>
       *
       * <pre>
       * When the z attribute is not present
       * </pre>
       */
      boolean hasZNull();
      /**
       * <code>optional bool z_null = 5 [default = false];</code>
       *
       * <pre>
       * When the z attribute is not present
       * </pre>
       */
      boolean getZNull();
    }
    /**
     * Protobuf type {@code ThingModel.Proto.Property.Location}
     */
    public static final class Location extends
        com.google.protobuf.GeneratedMessage
        implements LocationOrBuilder {
      // Use Location.newBuilder() to construct.
      private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Location defaultInstance;
      public static Location getDefaultInstance() {
        return defaultInstance;
      }

      public Location getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Location(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                x_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                y_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                z_ = input.readDouble();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                stringSystem_ = input.readInt32();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                zNull_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Location.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Location> PARSER =
          new com.google.protobuf.AbstractParser<Location>() {
        public Location parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Location(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Location> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required double x = 1 [default = 0];
      public static final int X_FIELD_NUMBER = 1;
      private double x_;
      /**
       * <code>required double x = 1 [default = 0];</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double x = 1 [default = 0];</code>
       */
      public double getX() {
        return x_;
      }

      // required double y = 2 [default = 0];
      public static final int Y_FIELD_NUMBER = 2;
      private double y_;
      /**
       * <code>required double y = 2 [default = 0];</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double y = 2 [default = 0];</code>
       */
      public double getY() {
        return y_;
      }

      // optional double z = 3 [default = 0];
      public static final int Z_FIELD_NUMBER = 3;
      private double z_;
      /**
       * <code>optional double z = 3 [default = 0];</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double z = 3 [default = 0];</code>
       */
      public double getZ() {
        return z_;
      }

      // optional int32 string_system = 4;
      public static final int STRING_SYSTEM_FIELD_NUMBER = 4;
      private int stringSystem_;
      /**
       * <code>optional int32 string_system = 4;</code>
       *
       * <pre>
       * WGS84 by default
       * </pre>
       */
      public boolean hasStringSystem() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 string_system = 4;</code>
       *
       * <pre>
       * WGS84 by default
       * </pre>
       */
      public int getStringSystem() {
        return stringSystem_;
      }

      // optional bool z_null = 5 [default = false];
      public static final int Z_NULL_FIELD_NUMBER = 5;
      private boolean zNull_;
      /**
       * <code>optional bool z_null = 5 [default = false];</code>
       *
       * <pre>
       * When the z attribute is not present
       * </pre>
       */
      public boolean hasZNull() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool z_null = 5 [default = false];</code>
       *
       * <pre>
       * When the z attribute is not present
       * </pre>
       */
      public boolean getZNull() {
        return zNull_;
      }

      private void initFields() {
        x_ = 0D;
        y_ = 0D;
        z_ = 0D;
        stringSystem_ = 0;
        zNull_ = false;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, z_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, stringSystem_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBool(5, zNull_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, z_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, stringSystem_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(5, zNull_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Location parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Location parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Location parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Location parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Location parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Location parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Location parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Location parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Location parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Location parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Location prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ThingModel.Proto.Property.Location}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements LocationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoProperty.internal_static_ThingModel_Proto_Property_Location_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoProperty.internal_static_ThingModel_Proto_Property_Location_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Location.class, Builder.class);
        }

        // Construct using org.thingmodel.proto.ProtoProperty.Property.Location.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          x_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          z_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          stringSystem_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          zNull_ = false;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoProperty.internal_static_ThingModel_Proto_Property_Location_descriptor;
        }

        public Location getDefaultInstanceForType() {
          return Location.getDefaultInstance();
        }

        public Location build() {
          Location result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Location buildPartial() {
          Location result = new Location(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.z_ = z_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.stringSystem_ = stringSystem_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.zNull_ = zNull_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Location) {
            return mergeFrom((Location)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Location other) {
          if (other == Location.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          if (other.hasZ()) {
            setZ(other.getZ());
          }
          if (other.hasStringSystem()) {
            setStringSystem(other.getStringSystem());
          }
          if (other.hasZNull()) {
            setZNull(other.getZNull());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Location parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Location) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required double x = 1 [default = 0];
        private double x_ ;
        /**
         * <code>required double x = 1 [default = 0];</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required double x = 1 [default = 0];</code>
         */
        public double getX() {
          return x_;
        }
        /**
         * <code>required double x = 1 [default = 0];</code>
         */
        public Builder setX(double value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double x = 1 [default = 0];</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0D;
          onChanged();
          return this;
        }

        // required double y = 2 [default = 0];
        private double y_ ;
        /**
         * <code>required double y = 2 [default = 0];</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double y = 2 [default = 0];</code>
         */
        public double getY() {
          return y_;
        }
        /**
         * <code>required double y = 2 [default = 0];</code>
         */
        public Builder setY(double value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double y = 2 [default = 0];</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0D;
          onChanged();
          return this;
        }

        // optional double z = 3 [default = 0];
        private double z_ ;
        /**
         * <code>optional double z = 3 [default = 0];</code>
         */
        public boolean hasZ() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional double z = 3 [default = 0];</code>
         */
        public double getZ() {
          return z_;
        }
        /**
         * <code>optional double z = 3 [default = 0];</code>
         */
        public Builder setZ(double value) {
          bitField0_ |= 0x00000004;
          z_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double z = 3 [default = 0];</code>
         */
        public Builder clearZ() {
          bitField0_ = (bitField0_ & ~0x00000004);
          z_ = 0D;
          onChanged();
          return this;
        }

        // optional int32 string_system = 4;
        private int stringSystem_ ;
        /**
         * <code>optional int32 string_system = 4;</code>
         *
         * <pre>
         * WGS84 by default
         * </pre>
         */
        public boolean hasStringSystem() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 string_system = 4;</code>
         *
         * <pre>
         * WGS84 by default
         * </pre>
         */
        public int getStringSystem() {
          return stringSystem_;
        }
        /**
         * <code>optional int32 string_system = 4;</code>
         *
         * <pre>
         * WGS84 by default
         * </pre>
         */
        public Builder setStringSystem(int value) {
          bitField0_ |= 0x00000008;
          stringSystem_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 string_system = 4;</code>
         *
         * <pre>
         * WGS84 by default
         * </pre>
         */
        public Builder clearStringSystem() {
          bitField0_ = (bitField0_ & ~0x00000008);
          stringSystem_ = 0;
          onChanged();
          return this;
        }

        // optional bool z_null = 5 [default = false];
        private boolean zNull_ ;
        /**
         * <code>optional bool z_null = 5 [default = false];</code>
         *
         * <pre>
         * When the z attribute is not present
         * </pre>
         */
        public boolean hasZNull() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional bool z_null = 5 [default = false];</code>
         *
         * <pre>
         * When the z attribute is not present
         * </pre>
         */
        public boolean getZNull() {
          return zNull_;
        }
        /**
         * <code>optional bool z_null = 5 [default = false];</code>
         *
         * <pre>
         * When the z attribute is not present
         * </pre>
         */
        public Builder setZNull(boolean value) {
          bitField0_ |= 0x00000010;
          zNull_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool z_null = 5 [default = false];</code>
         *
         * <pre>
         * When the z attribute is not present
         * </pre>
         */
        public Builder clearZNull() {
          bitField0_ = (bitField0_ & ~0x00000010);
          zNull_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ThingModel.Proto.Property.Location)
      }

      static {
        defaultInstance = new Location(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ThingModel.Proto.Property.Location)
    }

    public interface StringOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string value = 1;
      /**
       * <code>optional string value = 1;</code>
       */
      boolean hasValue();
      /**
       * <code>optional string value = 1;</code>
       */
      java.lang.String getValue();
      /**
       * <code>optional string value = 1;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();

      // optional int32 string_value = 2 [default = 0];
      /**
       * <code>optional int32 string_value = 2 [default = 0];</code>
       *
       * <pre>
       **
       *	A string can be cached using StringDeclaration
       *	It's just an option, and a developer
       *	is allowed to ignore this feature
       *	when he want to send a string property.
       * </pre>
       */
      boolean hasStringValue();
      /**
       * <code>optional int32 string_value = 2 [default = 0];</code>
       *
       * <pre>
       **
       *	A string can be cached using StringDeclaration
       *	It's just an option, and a developer
       *	is allowed to ignore this feature
       *	when he want to send a string property.
       * </pre>
       */
      int getStringValue();
    }
    /**
     * Protobuf type {@code ThingModel.Proto.Property.String}
     */
    public static final class String extends
        com.google.protobuf.GeneratedMessage
        implements StringOrBuilder {
      // Use String.newBuilder() to construct.
      private String(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private String(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final String defaultInstance;
      public static String getDefaultInstance() {
        return defaultInstance;
      }

      public String getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private String(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                value_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                stringValue_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_String_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_String_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                String.class, Builder.class);
      }

      public static com.google.protobuf.Parser<String> PARSER =
          new com.google.protobuf.AbstractParser<String>() {
        public String parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new String(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<String> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private Object value_;
      /**
       * <code>optional string value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public java.lang.String getValue() {
        Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 string_value = 2 [default = 0];
      public static final int STRING_VALUE_FIELD_NUMBER = 2;
      private int stringValue_;
      /**
       * <code>optional int32 string_value = 2 [default = 0];</code>
       *
       * <pre>
       **
       *	A string can be cached using StringDeclaration
       *	It's just an option, and a developer
       *	is allowed to ignore this feature
       *	when he want to send a string property.
       * </pre>
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 string_value = 2 [default = 0];</code>
       *
       * <pre>
       **
       *	A string can be cached using StringDeclaration
       *	It's just an option, and a developer
       *	is allowed to ignore this feature
       *	when he want to send a string property.
       * </pre>
       */
      public int getStringValue() {
        return stringValue_;
      }

      private void initFields() {
        value_ = "";
        stringValue_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getValueBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, stringValue_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getValueBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, stringValue_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static String parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static String parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static String parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static String parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static String parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static String parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static String parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static String parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static String parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static String parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(String prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ThingModel.Proto.Property.String}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements StringOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoProperty.internal_static_ThingModel_Proto_Property_String_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoProperty.internal_static_ThingModel_Proto_Property_String_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  String.class, Builder.class);
        }

        // Construct using org.thingmodel.proto.ProtoProperty.Property.String.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          stringValue_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoProperty.internal_static_ThingModel_Proto_Property_String_descriptor;
        }

        public String getDefaultInstanceForType() {
          return String.getDefaultInstance();
        }

        public String build() {
          String result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public String buildPartial() {
          String result = new String(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.value_ = value_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.stringValue_ = stringValue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof String) {
            return mergeFrom((String)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(String other) {
          if (other == String.getDefaultInstance()) return this;
          if (other.hasValue()) {
            bitField0_ |= 0x00000001;
            value_ = other.value_;
            onChanged();
          }
          if (other.hasStringValue()) {
            setStringValue(other.getStringValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          String parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (String) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string value = 1;
        private Object value_ = "";
        /**
         * <code>optional string value = 1;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string value = 1;</code>
         */
        public java.lang.String getValue() {
          Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string value = 1;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string value = 1;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 1;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 1;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          value_ = value;
          onChanged();
          return this;
        }

        // optional int32 string_value = 2 [default = 0];
        private int stringValue_ ;
        /**
         * <code>optional int32 string_value = 2 [default = 0];</code>
         *
         * <pre>
         **
         *	A string can be cached using StringDeclaration
         *	It's just an option, and a developer
         *	is allowed to ignore this feature
         *	when he want to send a string property.
         * </pre>
         */
        public boolean hasStringValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 string_value = 2 [default = 0];</code>
         *
         * <pre>
         **
         *	A string can be cached using StringDeclaration
         *	It's just an option, and a developer
         *	is allowed to ignore this feature
         *	when he want to send a string property.
         * </pre>
         */
        public int getStringValue() {
          return stringValue_;
        }
        /**
         * <code>optional int32 string_value = 2 [default = 0];</code>
         *
         * <pre>
         **
         *	A string can be cached using StringDeclaration
         *	It's just an option, and a developer
         *	is allowed to ignore this feature
         *	when he want to send a string property.
         * </pre>
         */
        public Builder setStringValue(int value) {
          bitField0_ |= 0x00000002;
          stringValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 string_value = 2 [default = 0];</code>
         *
         * <pre>
         **
         *	A string can be cached using StringDeclaration
         *	It's just an option, and a developer
         *	is allowed to ignore this feature
         *	when he want to send a string property.
         * </pre>
         */
        public Builder clearStringValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          stringValue_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ThingModel.Proto.Property.String)
      }

      static {
        defaultInstance = new String(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ThingModel.Proto.Property.String)
    }

    private int bitField0_;
    // required int32 string_key = 1;
    public static final int STRING_KEY_FIELD_NUMBER = 1;
    private int stringKey_;
    /**
     * <code>required int32 string_key = 1;</code>
     */
    public boolean hasStringKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 string_key = 1;</code>
     */
    public int getStringKey() {
      return stringKey_;
    }

    // required .ThingModel.Proto.Property.Type type = 2 [default = STRING];
    public static final int TYPE_FIELD_NUMBER = 2;
    private Type type_;
    /**
     * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
     */
    public Type getType() {
      return type_;
    }

    // optional .ThingModel.Proto.Property.Location location_value = 3;
    public static final int LOCATION_VALUE_FIELD_NUMBER = 3;
    private Location locationValue_;
    /**
     * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
     */
    public boolean hasLocationValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
     */
    public Location getLocationValue() {
      return locationValue_;
    }
    /**
     * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
     */
    public LocationOrBuilder getLocationValueOrBuilder() {
      return locationValue_;
    }

    // optional .ThingModel.Proto.Property.String string_value = 4;
    public static final int STRING_VALUE_FIELD_NUMBER = 4;
    private String stringValue_;
    /**
     * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
     */
    public String getStringValue() {
      return stringValue_;
    }
    /**
     * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
     */
    public StringOrBuilder getStringValueOrBuilder() {
      return stringValue_;
    }

    // optional double double_value = 5;
    public static final int DOUBLE_VALUE_FIELD_NUMBER = 5;
    private double doubleValue_;
    /**
     * <code>optional double double_value = 5;</code>
     */
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double double_value = 5;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }

    // optional int32 int_value = 6;
    public static final int INT_VALUE_FIELD_NUMBER = 6;
    private int intValue_;
    /**
     * <code>optional int32 int_value = 6;</code>
     */
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 int_value = 6;</code>
     */
    public int getIntValue() {
      return intValue_;
    }

    // optional bool boolean_value = 7;
    public static final int BOOLEAN_VALUE_FIELD_NUMBER = 7;
    private boolean booleanValue_;
    /**
     * <code>optional bool boolean_value = 7;</code>
     */
    public boolean hasBooleanValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool boolean_value = 7;</code>
     */
    public boolean getBooleanValue() {
      return booleanValue_;
    }

    // optional int64 datetime_value = 8;
    public static final int DATETIME_VALUE_FIELD_NUMBER = 8;
    private long datetimeValue_;
    /**
     * <code>optional int64 datetime_value = 8;</code>
     */
    public boolean hasDatetimeValue() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 datetime_value = 8;</code>
     */
    public long getDatetimeValue() {
      return datetimeValue_;
    }

    private void initFields() {
      stringKey_ = 0;
      type_ = Type.STRING;
      locationValue_ = Location.getDefaultInstance();
      stringValue_ = String.getDefaultInstance();
      doubleValue_ = 0D;
      intValue_ = 0;
      booleanValue_ = false;
      datetimeValue_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStringKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLocationValue()) {
        if (!getLocationValue().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stringKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, locationValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, stringValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, doubleValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, intValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, booleanValue_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, datetimeValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stringKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, locationValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, stringValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, doubleValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, intValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, booleanValue_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, datetimeValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Property parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Property parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Property prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThingModel.Proto.Property}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Property.class, Builder.class);
      }

      // Construct using org.thingmodel.proto.ProtoProperty.Property.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationValueFieldBuilder();
          getStringValueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stringKey_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = Type.STRING;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (locationValueBuilder_ == null) {
          locationValue_ = Location.getDefaultInstance();
        } else {
          locationValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (stringValueBuilder_ == null) {
          stringValue_ = String.getDefaultInstance();
        } else {
          stringValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        intValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        booleanValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        datetimeValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoProperty.internal_static_ThingModel_Proto_Property_descriptor;
      }

      public Property getDefaultInstanceForType() {
        return Property.getDefaultInstance();
      }

      public Property build() {
        Property result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Property buildPartial() {
        Property result = new Property(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringKey_ = stringKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (locationValueBuilder_ == null) {
          result.locationValue_ = locationValue_;
        } else {
          result.locationValue_ = locationValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (stringValueBuilder_ == null) {
          result.stringValue_ = stringValue_;
        } else {
          result.stringValue_ = stringValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.doubleValue_ = doubleValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.intValue_ = intValue_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.booleanValue_ = booleanValue_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.datetimeValue_ = datetimeValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Property) {
          return mergeFrom((Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Property other) {
        if (other == Property.getDefaultInstance()) return this;
        if (other.hasStringKey()) {
          setStringKey(other.getStringKey());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLocationValue()) {
          mergeLocationValue(other.getLocationValue());
        }
        if (other.hasStringValue()) {
          mergeStringValue(other.getStringValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasBooleanValue()) {
          setBooleanValue(other.getBooleanValue());
        }
        if (other.hasDatetimeValue()) {
          setDatetimeValue(other.getDatetimeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStringKey()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (hasLocationValue()) {
          if (!getLocationValue().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Property parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Property) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 string_key = 1;
      private int stringKey_ ;
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public boolean hasStringKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public int getStringKey() {
        return stringKey_;
      }
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public Builder setStringKey(int value) {
        bitField0_ |= 0x00000001;
        stringKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public Builder clearStringKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringKey_ = 0;
        onChanged();
        return this;
      }

      // required .ThingModel.Proto.Property.Type type = 2 [default = STRING];
      private Type type_ = Type.STRING;
      /**
       * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
       */
      public Type getType() {
        return type_;
      }
      /**
       * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ThingModel.Proto.Property.Type type = 2 [default = STRING];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = Type.STRING;
        onChanged();
        return this;
      }

      // optional .ThingModel.Proto.Property.Location location_value = 3;
      private Location locationValue_ = Location.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Location, Location.Builder, LocationOrBuilder> locationValueBuilder_;
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public boolean hasLocationValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public Location getLocationValue() {
        if (locationValueBuilder_ == null) {
          return locationValue_;
        } else {
          return locationValueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public Builder setLocationValue(Location value) {
        if (locationValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          locationValue_ = value;
          onChanged();
        } else {
          locationValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public Builder setLocationValue(
          Location.Builder builderForValue) {
        if (locationValueBuilder_ == null) {
          locationValue_ = builderForValue.build();
          onChanged();
        } else {
          locationValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public Builder mergeLocationValue(Location value) {
        if (locationValueBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              locationValue_ != Location.getDefaultInstance()) {
            locationValue_ =
              Location.newBuilder(locationValue_).mergeFrom(value).buildPartial();
          } else {
            locationValue_ = value;
          }
          onChanged();
        } else {
          locationValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public Builder clearLocationValue() {
        if (locationValueBuilder_ == null) {
          locationValue_ = Location.getDefaultInstance();
          onChanged();
        } else {
          locationValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public Location.Builder getLocationValueBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLocationValueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      public LocationOrBuilder getLocationValueOrBuilder() {
        if (locationValueBuilder_ != null) {
          return locationValueBuilder_.getMessageOrBuilder();
        } else {
          return locationValue_;
        }
      }
      /**
       * <code>optional .ThingModel.Proto.Property.Location location_value = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Location, Location.Builder, LocationOrBuilder>
          getLocationValueFieldBuilder() {
        if (locationValueBuilder_ == null) {
          locationValueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Location, Location.Builder, LocationOrBuilder>(
                  locationValue_,
                  getParentForChildren(),
                  isClean());
          locationValue_ = null;
        }
        return locationValueBuilder_;
      }

      // optional .ThingModel.Proto.Property.String string_value = 4;
      private String stringValue_ = String.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          String, String.Builder, StringOrBuilder> stringValueBuilder_;
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public String getStringValue() {
        if (stringValueBuilder_ == null) {
          return stringValue_;
        } else {
          return stringValueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public Builder setStringValue(String value) {
        if (stringValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringValue_ = value;
          onChanged();
        } else {
          stringValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public Builder setStringValue(
          String.Builder builderForValue) {
        if (stringValueBuilder_ == null) {
          stringValue_ = builderForValue.build();
          onChanged();
        } else {
          stringValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public Builder mergeStringValue(String value) {
        if (stringValueBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              stringValue_ != String.getDefaultInstance()) {
            stringValue_ =
              String.newBuilder(stringValue_).mergeFrom(value).buildPartial();
          } else {
            stringValue_ = value;
          }
          onChanged();
        } else {
          stringValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public Builder clearStringValue() {
        if (stringValueBuilder_ == null) {
          stringValue_ = String.getDefaultInstance();
          onChanged();
        } else {
          stringValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public String.Builder getStringValueBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getStringValueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      public StringOrBuilder getStringValueOrBuilder() {
        if (stringValueBuilder_ != null) {
          return stringValueBuilder_.getMessageOrBuilder();
        } else {
          return stringValue_;
        }
      }
      /**
       * <code>optional .ThingModel.Proto.Property.String string_value = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          String, String.Builder, StringOrBuilder>
          getStringValueFieldBuilder() {
        if (stringValueBuilder_ == null) {
          stringValueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              String, String.Builder, StringOrBuilder>(
                  stringValue_,
                  getParentForChildren(),
                  isClean());
          stringValue_ = null;
        }
        return stringValueBuilder_;
      }

      // optional double double_value = 5;
      private double doubleValue_ ;
      /**
       * <code>optional double double_value = 5;</code>
       */
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double double_value = 5;</code>
       */
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>optional double double_value = 5;</code>
       */
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000010;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double double_value = 5;</code>
       */
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      // optional int32 int_value = 6;
      private int intValue_ ;
      /**
       * <code>optional int32 int_value = 6;</code>
       */
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 int_value = 6;</code>
       */
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>optional int32 int_value = 6;</code>
       */
      public Builder setIntValue(int value) {
        bitField0_ |= 0x00000020;
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int_value = 6;</code>
       */
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        intValue_ = 0;
        onChanged();
        return this;
      }

      // optional bool boolean_value = 7;
      private boolean booleanValue_ ;
      /**
       * <code>optional bool boolean_value = 7;</code>
       */
      public boolean hasBooleanValue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool boolean_value = 7;</code>
       */
      public boolean getBooleanValue() {
        return booleanValue_;
      }
      /**
       * <code>optional bool boolean_value = 7;</code>
       */
      public Builder setBooleanValue(boolean value) {
        bitField0_ |= 0x00000040;
        booleanValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolean_value = 7;</code>
       */
      public Builder clearBooleanValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        booleanValue_ = false;
        onChanged();
        return this;
      }

      // optional int64 datetime_value = 8;
      private long datetimeValue_ ;
      /**
       * <code>optional int64 datetime_value = 8;</code>
       */
      public boolean hasDatetimeValue() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 datetime_value = 8;</code>
       */
      public long getDatetimeValue() {
        return datetimeValue_;
      }
      /**
       * <code>optional int64 datetime_value = 8;</code>
       */
      public Builder setDatetimeValue(long value) {
        bitField0_ |= 0x00000080;
        datetimeValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 datetime_value = 8;</code>
       */
      public Builder clearDatetimeValue() {
        bitField0_ = (bitField0_ & ~0x00000080);
        datetimeValue_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ThingModel.Proto.Property)
    }

    static {
      defaultInstance = new Property(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ThingModel.Proto.Property)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_Property_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_Property_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_Property_Location_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_Property_String_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_Property_String_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Property.proto\022\020ThingModel.Proto\"\300\004\n\010P" +
      "roperty\022\022\n\nstring_key\030\001 \002(\005\0225\n\004type\030\002 \002(" +
      "\0162\037.ThingModel.Proto.Property.Type:\006STRI" +
      "NG\022;\n\016location_value\030\003 \001(\0132#.ThingModel." +
      "Proto.Property.Location\0227\n\014string_value\030" +
      "\004 \001(\0132!.ThingModel.Proto.Property.String" +
      "\022\024\n\014double_value\030\005 \001(\001\022\021\n\tint_value\030\006 \001(" +
      "\005\022\025\n\rboolean_value\030\007 \001(\010\022\026\n\016datetime_val" +
      "ue\030\010 \001(\003\032b\n\010Location\022\014\n\001x\030\001 \002(\001:\0010\022\014\n\001y\030" +
      "\002 \002(\001:\0010\022\014\n\001z\030\003 \001(\001:\0010\022\025\n\rstring_system\030",
      "\004 \001(\005\022\025\n\006z_null\030\005 \001(\010:\005false\0320\n\006String\022\r" +
      "\n\005value\030\001 \001(\t\022\027\n\014string_value\030\002 \001(\005:\0010\"\204" +
      "\001\n\004Type\022\022\n\016LOCATION_POINT\020\000\022\023\n\017LOCATION_" +
      "LATLNG\020\001\022\027\n\023LOCATION_EQUATORIAL\020\002\022\n\n\006STR" +
      "ING\020\003\022\n\n\006DOUBLE\020\004\022\007\n\003INT\020\005\022\013\n\007BOOLEAN\020\006\022" +
      "\014\n\010DATETIME\020\007B%\n\024org.thingmodel.protoB\rP" +
      "rotoProperty"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ThingModel_Proto_Property_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ThingModel_Proto_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_Property_descriptor,
              new String[] { "StringKey", "Type", "LocationValue", "StringValue", "DoubleValue", "IntValue", "BooleanValue", "DatetimeValue", });
          internal_static_ThingModel_Proto_Property_Location_descriptor =
            internal_static_ThingModel_Proto_Property_descriptor.getNestedTypes().get(0);
          internal_static_ThingModel_Proto_Property_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_Property_Location_descriptor,
              new String[] { "X", "Y", "Z", "StringSystem", "ZNull", });
          internal_static_ThingModel_Proto_Property_String_descriptor =
            internal_static_ThingModel_Proto_Property_descriptor.getNestedTypes().get(1);
          internal_static_ThingModel_Proto_Property_String_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_Property_String_descriptor,
              new String[] { "Value", "StringValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
