// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

package org.thingmodel.proto;

public final class ProtoTransaction {
  private ProtoTransaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransactionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    java.util.List<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration> 
        getStringDeclarationsList();
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration getStringDeclarations(int index);
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    int getStringDeclarationsCount();
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    java.util.List<? extends org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder> 
        getStringDeclarationsOrBuilderList();
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder getStringDeclarationsOrBuilder(
            int index);

    // repeated .ThingModel.Proto.Thing things_publish_list = 2;
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    java.util.List<ProtoThing.Thing>
        getThingsPublishListList();
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    ProtoThing.Thing getThingsPublishList(int index);
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    int getThingsPublishListCount();
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    java.util.List<? extends ProtoThing.ThingOrBuilder>
        getThingsPublishListOrBuilderList();
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    ProtoThing.ThingOrBuilder getThingsPublishListOrBuilder(
            int index);

    // repeated int32 things_remove_list = 3 [packed = true];
    /**
     * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
     */
    java.util.List<Integer> getThingsRemoveListList();
    /**
     * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
     */
    int getThingsRemoveListCount();
    /**
     * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
     */
    int getThingsRemoveList(int index);

    // repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    java.util.List<ProtoThingType.ThingType>
        getThingtypesDeclarationListList();
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    ProtoThingType.ThingType getThingtypesDeclarationList(int index);
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    int getThingtypesDeclarationListCount();
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    java.util.List<? extends ProtoThingType.ThingTypeOrBuilder>
        getThingtypesDeclarationListOrBuilderList();
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    ProtoThingType.ThingTypeOrBuilder getThingtypesDeclarationListOrBuilder(
            int index);

    // required int32 string_sender_id = 5;
    /**
     * <code>required int32 string_sender_id = 5;</code>
     *
     * <pre>
     * Identification of the sender
     * </pre>
     */
    boolean hasStringSenderId();
    /**
     * <code>required int32 string_sender_id = 5;</code>
     *
     * <pre>
     * Identification of the sender
     * </pre>
     */
    int getStringSenderId();
  }
  /**
   * Protobuf type {@code ThingModel.Proto.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage
      implements TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                stringDeclarations_ = new java.util.ArrayList<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration>();
                mutable_bitField0_ |= 0x00000001;
              }
              stringDeclarations_.add(input.readMessage(org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                thingsPublishList_ = new java.util.ArrayList<ProtoThing.Thing>();
                mutable_bitField0_ |= 0x00000002;
              }
              thingsPublishList_.add(input.readMessage(ProtoThing.Thing.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                thingsRemoveList_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              thingsRemoveList_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                thingsRemoveList_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                thingsRemoveList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                thingtypesDeclarationList_ = new java.util.ArrayList<ProtoThingType.ThingType>();
                mutable_bitField0_ |= 0x00000008;
              }
              thingtypesDeclarationList_.add(input.readMessage(ProtoThingType.ThingType.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              bitField0_ |= 0x00000001;
              stringSenderId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          stringDeclarations_ = java.util.Collections.unmodifiableList(stringDeclarations_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          thingsPublishList_ = java.util.Collections.unmodifiableList(thingsPublishList_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          thingsRemoveList_ = java.util.Collections.unmodifiableList(thingsRemoveList_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          thingtypesDeclarationList_ = java.util.Collections.unmodifiableList(thingtypesDeclarationList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoTransaction.internal_static_ThingModel_Proto_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoTransaction.internal_static_ThingModel_Proto_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transaction.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;
    public static final int STRING_DECLARATIONS_FIELD_NUMBER = 1;
    private java.util.List<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration> stringDeclarations_;
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    public java.util.List<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration> getStringDeclarationsList() {
      return stringDeclarations_;
    }
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    public java.util.List<? extends org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder> 
        getStringDeclarationsOrBuilderList() {
      return stringDeclarations_;
    }
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    public int getStringDeclarationsCount() {
      return stringDeclarations_.size();
    }
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    public org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration getStringDeclarations(int index) {
      return stringDeclarations_.get(index);
    }
    /**
     * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
     */
    public org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder getStringDeclarationsOrBuilder(
        int index) {
      return stringDeclarations_.get(index);
    }

    // repeated .ThingModel.Proto.Thing things_publish_list = 2;
    public static final int THINGS_PUBLISH_LIST_FIELD_NUMBER = 2;
    private java.util.List<ProtoThing.Thing> thingsPublishList_;
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    public java.util.List<ProtoThing.Thing> getThingsPublishListList() {
      return thingsPublishList_;
    }
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    public java.util.List<? extends ProtoThing.ThingOrBuilder>
        getThingsPublishListOrBuilderList() {
      return thingsPublishList_;
    }
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    public int getThingsPublishListCount() {
      return thingsPublishList_.size();
    }
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    public ProtoThing.Thing getThingsPublishList(int index) {
      return thingsPublishList_.get(index);
    }
    /**
     * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
     */
    public ProtoThing.ThingOrBuilder getThingsPublishListOrBuilder(
        int index) {
      return thingsPublishList_.get(index);
    }

    // repeated int32 things_remove_list = 3 [packed = true];
    public static final int THINGS_REMOVE_LIST_FIELD_NUMBER = 3;
    private java.util.List<Integer> thingsRemoveList_;
    /**
     * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
     */
    public java.util.List<Integer>
        getThingsRemoveListList() {
      return thingsRemoveList_;
    }
    /**
     * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
     */
    public int getThingsRemoveListCount() {
      return thingsRemoveList_.size();
    }
    /**
     * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
     */
    public int getThingsRemoveList(int index) {
      return thingsRemoveList_.get(index);
    }
    private int thingsRemoveListMemoizedSerializedSize = -1;

    // repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;
    public static final int THINGTYPES_DECLARATION_LIST_FIELD_NUMBER = 4;
    private java.util.List<ProtoThingType.ThingType> thingtypesDeclarationList_;
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    public java.util.List<ProtoThingType.ThingType> getThingtypesDeclarationListList() {
      return thingtypesDeclarationList_;
    }
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    public java.util.List<? extends ProtoThingType.ThingTypeOrBuilder>
        getThingtypesDeclarationListOrBuilderList() {
      return thingtypesDeclarationList_;
    }
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    public int getThingtypesDeclarationListCount() {
      return thingtypesDeclarationList_.size();
    }
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    public ProtoThingType.ThingType getThingtypesDeclarationList(int index) {
      return thingtypesDeclarationList_.get(index);
    }
    /**
     * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
     *
     * <pre>
     * Can be declared once
     * And we can't remove a ThingType
     * </pre>
     */
    public ProtoThingType.ThingTypeOrBuilder getThingtypesDeclarationListOrBuilder(
        int index) {
      return thingtypesDeclarationList_.get(index);
    }

    // required int32 string_sender_id = 5;
    public static final int STRING_SENDER_ID_FIELD_NUMBER = 5;
    private int stringSenderId_;
    /**
     * <code>required int32 string_sender_id = 5;</code>
     *
     * <pre>
     * Identification of the sender
     * </pre>
     */
    public boolean hasStringSenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 string_sender_id = 5;</code>
     *
     * <pre>
     * Identification of the sender
     * </pre>
     */
    public int getStringSenderId() {
      return stringSenderId_;
    }

    private void initFields() {
      stringDeclarations_ = java.util.Collections.emptyList();
      thingsPublishList_ = java.util.Collections.emptyList();
      thingsRemoveList_ = java.util.Collections.emptyList();
      thingtypesDeclarationList_ = java.util.Collections.emptyList();
      stringSenderId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStringSenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getStringDeclarationsCount(); i++) {
        if (!getStringDeclarations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getThingsPublishListCount(); i++) {
        if (!getThingsPublishList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getThingtypesDeclarationListCount(); i++) {
        if (!getThingtypesDeclarationList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < stringDeclarations_.size(); i++) {
        output.writeMessage(1, stringDeclarations_.get(i));
      }
      for (int i = 0; i < thingsPublishList_.size(); i++) {
        output.writeMessage(2, thingsPublishList_.get(i));
      }
      if (getThingsRemoveListList().size() > 0) {
        output.writeRawVarint32(26);
        output.writeRawVarint32(thingsRemoveListMemoizedSerializedSize);
      }
      for (int i = 0; i < thingsRemoveList_.size(); i++) {
        output.writeInt32NoTag(thingsRemoveList_.get(i));
      }
      for (int i = 0; i < thingtypesDeclarationList_.size(); i++) {
        output.writeMessage(4, thingtypesDeclarationList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(5, stringSenderId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stringDeclarations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stringDeclarations_.get(i));
      }
      for (int i = 0; i < thingsPublishList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, thingsPublishList_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < thingsRemoveList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(thingsRemoveList_.get(i));
        }
        size += dataSize;
        if (!getThingsRemoveListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        thingsRemoveListMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < thingtypesDeclarationList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, thingtypesDeclarationList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, stringSenderId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThingModel.Proto.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoTransaction.internal_static_ThingModel_Proto_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoTransaction.internal_static_ThingModel_Proto_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transaction.class, Builder.class);
      }

      // Construct using org.thingmodel.proto.ProtoTransaction.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStringDeclarationsFieldBuilder();
          getThingsPublishListFieldBuilder();
          getThingtypesDeclarationListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (stringDeclarationsBuilder_ == null) {
          stringDeclarations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stringDeclarationsBuilder_.clear();
        }
        if (thingsPublishListBuilder_ == null) {
          thingsPublishList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          thingsPublishListBuilder_.clear();
        }
        thingsRemoveList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (thingtypesDeclarationListBuilder_ == null) {
          thingtypesDeclarationList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          thingtypesDeclarationListBuilder_.clear();
        }
        stringSenderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoTransaction.internal_static_ThingModel_Proto_Transaction_descriptor;
      }

      public Transaction getDefaultInstanceForType() {
        return Transaction.getDefaultInstance();
      }

      public Transaction build() {
        Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Transaction buildPartial() {
        Transaction result = new Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (stringDeclarationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            stringDeclarations_ = java.util.Collections.unmodifiableList(stringDeclarations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stringDeclarations_ = stringDeclarations_;
        } else {
          result.stringDeclarations_ = stringDeclarationsBuilder_.build();
        }
        if (thingsPublishListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            thingsPublishList_ = java.util.Collections.unmodifiableList(thingsPublishList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.thingsPublishList_ = thingsPublishList_;
        } else {
          result.thingsPublishList_ = thingsPublishListBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          thingsRemoveList_ = java.util.Collections.unmodifiableList(thingsRemoveList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.thingsRemoveList_ = thingsRemoveList_;
        if (thingtypesDeclarationListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            thingtypesDeclarationList_ = java.util.Collections.unmodifiableList(thingtypesDeclarationList_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.thingtypesDeclarationList_ = thingtypesDeclarationList_;
        } else {
          result.thingtypesDeclarationList_ = thingtypesDeclarationListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringSenderId_ = stringSenderId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transaction) {
          return mergeFrom((Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transaction other) {
        if (other == Transaction.getDefaultInstance()) return this;
        if (stringDeclarationsBuilder_ == null) {
          if (!other.stringDeclarations_.isEmpty()) {
            if (stringDeclarations_.isEmpty()) {
              stringDeclarations_ = other.stringDeclarations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStringDeclarationsIsMutable();
              stringDeclarations_.addAll(other.stringDeclarations_);
            }
            onChanged();
          }
        } else {
          if (!other.stringDeclarations_.isEmpty()) {
            if (stringDeclarationsBuilder_.isEmpty()) {
              stringDeclarationsBuilder_.dispose();
              stringDeclarationsBuilder_ = null;
              stringDeclarations_ = other.stringDeclarations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stringDeclarationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStringDeclarationsFieldBuilder() : null;
            } else {
              stringDeclarationsBuilder_.addAllMessages(other.stringDeclarations_);
            }
          }
        }
        if (thingsPublishListBuilder_ == null) {
          if (!other.thingsPublishList_.isEmpty()) {
            if (thingsPublishList_.isEmpty()) {
              thingsPublishList_ = other.thingsPublishList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureThingsPublishListIsMutable();
              thingsPublishList_.addAll(other.thingsPublishList_);
            }
            onChanged();
          }
        } else {
          if (!other.thingsPublishList_.isEmpty()) {
            if (thingsPublishListBuilder_.isEmpty()) {
              thingsPublishListBuilder_.dispose();
              thingsPublishListBuilder_ = null;
              thingsPublishList_ = other.thingsPublishList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              thingsPublishListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getThingsPublishListFieldBuilder() : null;
            } else {
              thingsPublishListBuilder_.addAllMessages(other.thingsPublishList_);
            }
          }
        }
        if (!other.thingsRemoveList_.isEmpty()) {
          if (thingsRemoveList_.isEmpty()) {
            thingsRemoveList_ = other.thingsRemoveList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureThingsRemoveListIsMutable();
            thingsRemoveList_.addAll(other.thingsRemoveList_);
          }
          onChanged();
        }
        if (thingtypesDeclarationListBuilder_ == null) {
          if (!other.thingtypesDeclarationList_.isEmpty()) {
            if (thingtypesDeclarationList_.isEmpty()) {
              thingtypesDeclarationList_ = other.thingtypesDeclarationList_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureThingtypesDeclarationListIsMutable();
              thingtypesDeclarationList_.addAll(other.thingtypesDeclarationList_);
            }
            onChanged();
          }
        } else {
          if (!other.thingtypesDeclarationList_.isEmpty()) {
            if (thingtypesDeclarationListBuilder_.isEmpty()) {
              thingtypesDeclarationListBuilder_.dispose();
              thingtypesDeclarationListBuilder_ = null;
              thingtypesDeclarationList_ = other.thingtypesDeclarationList_;
              bitField0_ = (bitField0_ & ~0x00000008);
              thingtypesDeclarationListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getThingtypesDeclarationListFieldBuilder() : null;
            } else {
              thingtypesDeclarationListBuilder_.addAllMessages(other.thingtypesDeclarationList_);
            }
          }
        }
        if (other.hasStringSenderId()) {
          setStringSenderId(other.getStringSenderId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStringSenderId()) {
          
          return false;
        }
        for (int i = 0; i < getStringDeclarationsCount(); i++) {
          if (!getStringDeclarations(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getThingsPublishListCount(); i++) {
          if (!getThingsPublishList(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getThingtypesDeclarationListCount(); i++) {
          if (!getThingtypesDeclarationList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;
      private java.util.List<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration> stringDeclarations_ =
        java.util.Collections.emptyList();
      private void ensureStringDeclarationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          stringDeclarations_ = new java.util.ArrayList<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration>(stringDeclarations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder, org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder> stringDeclarationsBuilder_;

      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public java.util.List<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration> getStringDeclarationsList() {
        if (stringDeclarationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stringDeclarations_);
        } else {
          return stringDeclarationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public int getStringDeclarationsCount() {
        if (stringDeclarationsBuilder_ == null) {
          return stringDeclarations_.size();
        } else {
          return stringDeclarationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration getStringDeclarations(int index) {
        if (stringDeclarationsBuilder_ == null) {
          return stringDeclarations_.get(index);
        } else {
          return stringDeclarationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder setStringDeclarations(
          int index, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration value) {
        if (stringDeclarationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.set(index, value);
          onChanged();
        } else {
          stringDeclarationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder setStringDeclarations(
          int index, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder builderForValue) {
        if (stringDeclarationsBuilder_ == null) {
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.set(index, builderForValue.build());
          onChanged();
        } else {
          stringDeclarationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder addStringDeclarations(org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration value) {
        if (stringDeclarationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.add(value);
          onChanged();
        } else {
          stringDeclarationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder addStringDeclarations(
          int index, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration value) {
        if (stringDeclarationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.add(index, value);
          onChanged();
        } else {
          stringDeclarationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder addStringDeclarations(
          org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder builderForValue) {
        if (stringDeclarationsBuilder_ == null) {
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.add(builderForValue.build());
          onChanged();
        } else {
          stringDeclarationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder addStringDeclarations(
          int index, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder builderForValue) {
        if (stringDeclarationsBuilder_ == null) {
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.add(index, builderForValue.build());
          onChanged();
        } else {
          stringDeclarationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder addAllStringDeclarations(
          Iterable<? extends org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration> values) {
        if (stringDeclarationsBuilder_ == null) {
          ensureStringDeclarationsIsMutable();
          super.addAll(values, stringDeclarations_);
          onChanged();
        } else {
          stringDeclarationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder clearStringDeclarations() {
        if (stringDeclarationsBuilder_ == null) {
          stringDeclarations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stringDeclarationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public Builder removeStringDeclarations(int index) {
        if (stringDeclarationsBuilder_ == null) {
          ensureStringDeclarationsIsMutable();
          stringDeclarations_.remove(index);
          onChanged();
        } else {
          stringDeclarationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder getStringDeclarationsBuilder(
          int index) {
        return getStringDeclarationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder getStringDeclarationsOrBuilder(
          int index) {
        if (stringDeclarationsBuilder_ == null) {
          return stringDeclarations_.get(index);  } else {
          return stringDeclarationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public java.util.List<? extends org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder> 
           getStringDeclarationsOrBuilderList() {
        if (stringDeclarationsBuilder_ != null) {
          return stringDeclarationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stringDeclarations_);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder addStringDeclarationsBuilder() {
        return getStringDeclarationsFieldBuilder().addBuilder(
            org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder addStringDeclarationsBuilder(
          int index) {
        return getStringDeclarationsFieldBuilder().addBuilder(
            index, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.StringDeclaration string_declarations = 1;</code>
       */
      public java.util.List<org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder> 
           getStringDeclarationsBuilderList() {
        return getStringDeclarationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder, org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder> 
          getStringDeclarationsFieldBuilder() {
        if (stringDeclarationsBuilder_ == null) {
          stringDeclarationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration, org.thingmodel.proto.ProtoStringDeclaration.StringDeclaration.Builder, org.thingmodel.proto.ProtoStringDeclaration.StringDeclarationOrBuilder>(
                  stringDeclarations_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          stringDeclarations_ = null;
        }
        return stringDeclarationsBuilder_;
      }

      // repeated .ThingModel.Proto.Thing things_publish_list = 2;
      private java.util.List<ProtoThing.Thing> thingsPublishList_ =
        java.util.Collections.emptyList();
      private void ensureThingsPublishListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          thingsPublishList_ = new java.util.ArrayList<ProtoThing.Thing>(thingsPublishList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoThing.Thing, ProtoThing.Thing.Builder, ProtoThing.ThingOrBuilder> thingsPublishListBuilder_;

      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public java.util.List<ProtoThing.Thing> getThingsPublishListList() {
        if (thingsPublishListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(thingsPublishList_);
        } else {
          return thingsPublishListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public int getThingsPublishListCount() {
        if (thingsPublishListBuilder_ == null) {
          return thingsPublishList_.size();
        } else {
          return thingsPublishListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public ProtoThing.Thing getThingsPublishList(int index) {
        if (thingsPublishListBuilder_ == null) {
          return thingsPublishList_.get(index);
        } else {
          return thingsPublishListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder setThingsPublishList(
          int index, ProtoThing.Thing value) {
        if (thingsPublishListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingsPublishListIsMutable();
          thingsPublishList_.set(index, value);
          onChanged();
        } else {
          thingsPublishListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder setThingsPublishList(
          int index, ProtoThing.Thing.Builder builderForValue) {
        if (thingsPublishListBuilder_ == null) {
          ensureThingsPublishListIsMutable();
          thingsPublishList_.set(index, builderForValue.build());
          onChanged();
        } else {
          thingsPublishListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder addThingsPublishList(ProtoThing.Thing value) {
        if (thingsPublishListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingsPublishListIsMutable();
          thingsPublishList_.add(value);
          onChanged();
        } else {
          thingsPublishListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder addThingsPublishList(
          int index, ProtoThing.Thing value) {
        if (thingsPublishListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingsPublishListIsMutable();
          thingsPublishList_.add(index, value);
          onChanged();
        } else {
          thingsPublishListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder addThingsPublishList(
          ProtoThing.Thing.Builder builderForValue) {
        if (thingsPublishListBuilder_ == null) {
          ensureThingsPublishListIsMutable();
          thingsPublishList_.add(builderForValue.build());
          onChanged();
        } else {
          thingsPublishListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder addThingsPublishList(
          int index, ProtoThing.Thing.Builder builderForValue) {
        if (thingsPublishListBuilder_ == null) {
          ensureThingsPublishListIsMutable();
          thingsPublishList_.add(index, builderForValue.build());
          onChanged();
        } else {
          thingsPublishListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder addAllThingsPublishList(
          Iterable<? extends ProtoThing.Thing> values) {
        if (thingsPublishListBuilder_ == null) {
          ensureThingsPublishListIsMutable();
          super.addAll(values, thingsPublishList_);
          onChanged();
        } else {
          thingsPublishListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder clearThingsPublishList() {
        if (thingsPublishListBuilder_ == null) {
          thingsPublishList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          thingsPublishListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public Builder removeThingsPublishList(int index) {
        if (thingsPublishListBuilder_ == null) {
          ensureThingsPublishListIsMutable();
          thingsPublishList_.remove(index);
          onChanged();
        } else {
          thingsPublishListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public ProtoThing.Thing.Builder getThingsPublishListBuilder(
          int index) {
        return getThingsPublishListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public ProtoThing.ThingOrBuilder getThingsPublishListOrBuilder(
          int index) {
        if (thingsPublishListBuilder_ == null) {
          return thingsPublishList_.get(index);  } else {
          return thingsPublishListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public java.util.List<? extends ProtoThing.ThingOrBuilder>
           getThingsPublishListOrBuilderList() {
        if (thingsPublishListBuilder_ != null) {
          return thingsPublishListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(thingsPublishList_);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public ProtoThing.Thing.Builder addThingsPublishListBuilder() {
        return getThingsPublishListFieldBuilder().addBuilder(
            ProtoThing.Thing.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public ProtoThing.Thing.Builder addThingsPublishListBuilder(
          int index) {
        return getThingsPublishListFieldBuilder().addBuilder(
            index, ProtoThing.Thing.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.Thing things_publish_list = 2;</code>
       */
      public java.util.List<ProtoThing.Thing.Builder>
           getThingsPublishListBuilderList() {
        return getThingsPublishListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoThing.Thing, ProtoThing.Thing.Builder, ProtoThing.ThingOrBuilder>
          getThingsPublishListFieldBuilder() {
        if (thingsPublishListBuilder_ == null) {
          thingsPublishListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoThing.Thing, ProtoThing.Thing.Builder, ProtoThing.ThingOrBuilder>(
                  thingsPublishList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          thingsPublishList_ = null;
        }
        return thingsPublishListBuilder_;
      }

      // repeated int32 things_remove_list = 3 [packed = true];
      private java.util.List<Integer> thingsRemoveList_ = java.util.Collections.emptyList();
      private void ensureThingsRemoveListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          thingsRemoveList_ = new java.util.ArrayList<Integer>(thingsRemoveList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public java.util.List<Integer>
          getThingsRemoveListList() {
        return java.util.Collections.unmodifiableList(thingsRemoveList_);
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public int getThingsRemoveListCount() {
        return thingsRemoveList_.size();
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public int getThingsRemoveList(int index) {
        return thingsRemoveList_.get(index);
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public Builder setThingsRemoveList(
          int index, int value) {
        ensureThingsRemoveListIsMutable();
        thingsRemoveList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public Builder addThingsRemoveList(int value) {
        ensureThingsRemoveListIsMutable();
        thingsRemoveList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public Builder addAllThingsRemoveList(
          Iterable<? extends Integer> values) {
        ensureThingsRemoveListIsMutable();
        super.addAll(values, thingsRemoveList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 things_remove_list = 3 [packed = true];</code>
       */
      public Builder clearThingsRemoveList() {
        thingsRemoveList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;
      private java.util.List<ProtoThingType.ThingType> thingtypesDeclarationList_ =
        java.util.Collections.emptyList();
      private void ensureThingtypesDeclarationListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          thingtypesDeclarationList_ = new java.util.ArrayList<ProtoThingType.ThingType>(thingtypesDeclarationList_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoThingType.ThingType, ProtoThingType.ThingType.Builder, ProtoThingType.ThingTypeOrBuilder> thingtypesDeclarationListBuilder_;

      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public java.util.List<ProtoThingType.ThingType> getThingtypesDeclarationListList() {
        if (thingtypesDeclarationListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(thingtypesDeclarationList_);
        } else {
          return thingtypesDeclarationListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public int getThingtypesDeclarationListCount() {
        if (thingtypesDeclarationListBuilder_ == null) {
          return thingtypesDeclarationList_.size();
        } else {
          return thingtypesDeclarationListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public ProtoThingType.ThingType getThingtypesDeclarationList(int index) {
        if (thingtypesDeclarationListBuilder_ == null) {
          return thingtypesDeclarationList_.get(index);
        } else {
          return thingtypesDeclarationListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder setThingtypesDeclarationList(
          int index, ProtoThingType.ThingType value) {
        if (thingtypesDeclarationListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.set(index, value);
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder setThingtypesDeclarationList(
          int index, ProtoThingType.ThingType.Builder builderForValue) {
        if (thingtypesDeclarationListBuilder_ == null) {
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.set(index, builderForValue.build());
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder addThingtypesDeclarationList(ProtoThingType.ThingType value) {
        if (thingtypesDeclarationListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.add(value);
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder addThingtypesDeclarationList(
          int index, ProtoThingType.ThingType value) {
        if (thingtypesDeclarationListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.add(index, value);
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder addThingtypesDeclarationList(
          ProtoThingType.ThingType.Builder builderForValue) {
        if (thingtypesDeclarationListBuilder_ == null) {
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.add(builderForValue.build());
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder addThingtypesDeclarationList(
          int index, ProtoThingType.ThingType.Builder builderForValue) {
        if (thingtypesDeclarationListBuilder_ == null) {
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.add(index, builderForValue.build());
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder addAllThingtypesDeclarationList(
          Iterable<? extends ProtoThingType.ThingType> values) {
        if (thingtypesDeclarationListBuilder_ == null) {
          ensureThingtypesDeclarationListIsMutable();
          super.addAll(values, thingtypesDeclarationList_);
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder clearThingtypesDeclarationList() {
        if (thingtypesDeclarationListBuilder_ == null) {
          thingtypesDeclarationList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public Builder removeThingtypesDeclarationList(int index) {
        if (thingtypesDeclarationListBuilder_ == null) {
          ensureThingtypesDeclarationListIsMutable();
          thingtypesDeclarationList_.remove(index);
          onChanged();
        } else {
          thingtypesDeclarationListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public ProtoThingType.ThingType.Builder getThingtypesDeclarationListBuilder(
          int index) {
        return getThingtypesDeclarationListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public ProtoThingType.ThingTypeOrBuilder getThingtypesDeclarationListOrBuilder(
          int index) {
        if (thingtypesDeclarationListBuilder_ == null) {
          return thingtypesDeclarationList_.get(index);  } else {
          return thingtypesDeclarationListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public java.util.List<? extends ProtoThingType.ThingTypeOrBuilder>
           getThingtypesDeclarationListOrBuilderList() {
        if (thingtypesDeclarationListBuilder_ != null) {
          return thingtypesDeclarationListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(thingtypesDeclarationList_);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public ProtoThingType.ThingType.Builder addThingtypesDeclarationListBuilder() {
        return getThingtypesDeclarationListFieldBuilder().addBuilder(
            ProtoThingType.ThingType.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public ProtoThingType.ThingType.Builder addThingtypesDeclarationListBuilder(
          int index) {
        return getThingtypesDeclarationListFieldBuilder().addBuilder(
            index, ProtoThingType.ThingType.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.ThingType thingtypes_declaration_list = 4;</code>
       *
       * <pre>
       * Can be declared once
       * And we can't remove a ThingType
       * </pre>
       */
      public java.util.List<ProtoThingType.ThingType.Builder>
           getThingtypesDeclarationListBuilderList() {
        return getThingtypesDeclarationListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoThingType.ThingType, ProtoThingType.ThingType.Builder, ProtoThingType.ThingTypeOrBuilder>
          getThingtypesDeclarationListFieldBuilder() {
        if (thingtypesDeclarationListBuilder_ == null) {
          thingtypesDeclarationListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoThingType.ThingType, ProtoThingType.ThingType.Builder, ProtoThingType.ThingTypeOrBuilder>(
                  thingtypesDeclarationList_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          thingtypesDeclarationList_ = null;
        }
        return thingtypesDeclarationListBuilder_;
      }

      // required int32 string_sender_id = 5;
      private int stringSenderId_ ;
      /**
       * <code>required int32 string_sender_id = 5;</code>
       *
       * <pre>
       * Identification of the sender
       * </pre>
       */
      public boolean hasStringSenderId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 string_sender_id = 5;</code>
       *
       * <pre>
       * Identification of the sender
       * </pre>
       */
      public int getStringSenderId() {
        return stringSenderId_;
      }
      /**
       * <code>required int32 string_sender_id = 5;</code>
       *
       * <pre>
       * Identification of the sender
       * </pre>
       */
      public Builder setStringSenderId(int value) {
        bitField0_ |= 0x00000010;
        stringSenderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 string_sender_id = 5;</code>
       *
       * <pre>
       * Identification of the sender
       * </pre>
       */
      public Builder clearStringSenderId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        stringSenderId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ThingModel.Proto.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ThingModel.Proto.Transaction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021Transaction.proto\022\020ThingModel.Proto\032\027S" +
      "tringDeclaration.proto\032\013Thing.proto\032\017Thi" +
      "ngType.proto\"\201\002\n\013Transaction\022@\n\023string_d" +
      "eclarations\030\001 \003(\0132#.ThingModel.Proto.Str" +
      "ingDeclaration\0224\n\023things_publish_list\030\002 " +
      "\003(\0132\027.ThingModel.Proto.Thing\022\036\n\022things_r" +
      "emove_list\030\003 \003(\005B\002\020\001\022@\n\033thingtypes_decla" +
      "ration_list\030\004 \003(\0132\033.ThingModel.Proto.Thi" +
      "ngType\022\030\n\020string_sender_id\030\005 \002(\005B(\n\024org." +
      "thingmodel.protoB\020ProtoTransaction"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ThingModel_Proto_Transaction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ThingModel_Proto_Transaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_Transaction_descriptor,
              new String[] { "StringDeclarations", "ThingsPublishList", "ThingsRemoveList", "ThingtypesDeclarationList", "StringSenderId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.thingmodel.proto.ProtoStringDeclaration.getDescriptor(),
          ProtoThing.getDescriptor(),
          ProtoThingType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
