// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Thing.proto

package org.thingmodel.proto;

public final class ProtoThing {
  private ProtoThing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ThingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 string_id = 1;
    /**
     * <code>required int32 string_id = 1;</code>
     */
    boolean hasStringId();
    /**
     * <code>required int32 string_id = 1;</code>
     */
    int getStringId();

    // required int32 string_type_name = 2;
    /**
     * <code>required int32 string_type_name = 2;</code>
     */
    boolean hasStringTypeName();
    /**
     * <code>required int32 string_type_name = 2;</code>
     */
    int getStringTypeName();

    // repeated .ThingModel.Proto.Property properties = 3;
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    java.util.List<org.thingmodel.proto.ProtoProperty.Property> 
        getPropertiesList();
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    org.thingmodel.proto.ProtoProperty.Property getProperties(int index);
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    java.util.List<? extends org.thingmodel.proto.ProtoProperty.PropertyOrBuilder> 
        getPropertiesOrBuilderList();
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    org.thingmodel.proto.ProtoProperty.PropertyOrBuilder getPropertiesOrBuilder(
            int index);

    // repeated int32 connections = 4 [packed = true];
    /**
     * <code>repeated int32 connections = 4 [packed = true];</code>
     *
     * <pre>
     * Use int32 string ids
     * </pre>
     */
    java.util.List<Integer> getConnectionsList();
    /**
     * <code>repeated int32 connections = 4 [packed = true];</code>
     *
     * <pre>
     * Use int32 string ids
     * </pre>
     */
    int getConnectionsCount();
    /**
     * <code>repeated int32 connections = 4 [packed = true];</code>
     *
     * <pre>
     * Use int32 string ids
     * </pre>
     */
    int getConnections(int index);

    // optional bool connections_change = 5 [default = false];
    /**
     * <code>optional bool connections_change = 5 [default = false];</code>
     */
    boolean hasConnectionsChange();
    /**
     * <code>optional bool connections_change = 5 [default = false];</code>
     */
    boolean getConnectionsChange();
  }
  /**
   * Protobuf type {@code ThingModel.Proto.Thing}
   */
  public static final class Thing extends
      com.google.protobuf.GeneratedMessage
      implements ThingOrBuilder {
    // Use Thing.newBuilder() to construct.
    private Thing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Thing(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Thing defaultInstance;
    public static Thing getDefaultInstance() {
      return defaultInstance;
    }

    public Thing getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Thing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stringId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stringTypeName_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                properties_ = new java.util.ArrayList<org.thingmodel.proto.ProtoProperty.Property>();
                mutable_bitField0_ |= 0x00000004;
              }
              properties_.add(input.readMessage(org.thingmodel.proto.ProtoProperty.Property.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                connections_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              connections_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                connections_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                connections_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              connectionsChange_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          connections_ = java.util.Collections.unmodifiableList(connections_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoThing.internal_static_ThingModel_Proto_Thing_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoThing.internal_static_ThingModel_Proto_Thing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Thing.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Thing> PARSER =
        new com.google.protobuf.AbstractParser<Thing>() {
      public Thing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Thing(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Thing> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 string_id = 1;
    public static final int STRING_ID_FIELD_NUMBER = 1;
    private int stringId_;
    /**
     * <code>required int32 string_id = 1;</code>
     */
    public boolean hasStringId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 string_id = 1;</code>
     */
    public int getStringId() {
      return stringId_;
    }

    // required int32 string_type_name = 2;
    public static final int STRING_TYPE_NAME_FIELD_NUMBER = 2;
    private int stringTypeName_;
    /**
     * <code>required int32 string_type_name = 2;</code>
     */
    public boolean hasStringTypeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 string_type_name = 2;</code>
     */
    public int getStringTypeName() {
      return stringTypeName_;
    }

    // repeated .ThingModel.Proto.Property properties = 3;
    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private java.util.List<org.thingmodel.proto.ProtoProperty.Property> properties_;
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    public java.util.List<org.thingmodel.proto.ProtoProperty.Property> getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    public java.util.List<? extends org.thingmodel.proto.ProtoProperty.PropertyOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    public org.thingmodel.proto.ProtoProperty.Property getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
     */
    public org.thingmodel.proto.ProtoProperty.PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }

    // repeated int32 connections = 4 [packed = true];
    public static final int CONNECTIONS_FIELD_NUMBER = 4;
    private java.util.List<Integer> connections_;
    /**
     * <code>repeated int32 connections = 4 [packed = true];</code>
     *
     * <pre>
     * Use int32 string ids
     * </pre>
     */
    public java.util.List<Integer>
        getConnectionsList() {
      return connections_;
    }
    /**
     * <code>repeated int32 connections = 4 [packed = true];</code>
     *
     * <pre>
     * Use int32 string ids
     * </pre>
     */
    public int getConnectionsCount() {
      return connections_.size();
    }
    /**
     * <code>repeated int32 connections = 4 [packed = true];</code>
     *
     * <pre>
     * Use int32 string ids
     * </pre>
     */
    public int getConnections(int index) {
      return connections_.get(index);
    }
    private int connectionsMemoizedSerializedSize = -1;

    // optional bool connections_change = 5 [default = false];
    public static final int CONNECTIONS_CHANGE_FIELD_NUMBER = 5;
    private boolean connectionsChange_;
    /**
     * <code>optional bool connections_change = 5 [default = false];</code>
     */
    public boolean hasConnectionsChange() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool connections_change = 5 [default = false];</code>
     */
    public boolean getConnectionsChange() {
      return connectionsChange_;
    }

    private void initFields() {
      stringId_ = 0;
      stringTypeName_ = 0;
      properties_ = java.util.Collections.emptyList();
      connections_ = java.util.Collections.emptyList();
      connectionsChange_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStringId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStringTypeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertiesCount(); i++) {
        if (!getProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stringId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stringTypeName_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(3, properties_.get(i));
      }
      if (getConnectionsList().size() > 0) {
        output.writeRawVarint32(34);
        output.writeRawVarint32(connectionsMemoizedSerializedSize);
      }
      for (int i = 0; i < connections_.size(); i++) {
        output.writeInt32NoTag(connections_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(5, connectionsChange_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stringId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stringTypeName_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, properties_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < connections_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(connections_.get(i));
        }
        size += dataSize;
        if (!getConnectionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        connectionsMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, connectionsChange_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Thing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Thing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Thing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Thing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Thing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Thing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Thing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Thing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Thing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Thing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Thing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThingModel.Proto.Thing}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ThingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoThing.internal_static_ThingModel_Proto_Thing_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoThing.internal_static_ThingModel_Proto_Thing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Thing.class, Builder.class);
      }

      // Construct using org.thingmodel.proto.ProtoThing.Thing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stringId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        stringTypeName_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          propertiesBuilder_.clear();
        }
        connections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        connectionsChange_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoThing.internal_static_ThingModel_Proto_Thing_descriptor;
      }

      public Thing getDefaultInstanceForType() {
        return Thing.getDefaultInstance();
      }

      public Thing build() {
        Thing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Thing buildPartial() {
        Thing result = new Thing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringId_ = stringId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stringTypeName_ = stringTypeName_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          connections_ = java.util.Collections.unmodifiableList(connections_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.connections_ = connections_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.connectionsChange_ = connectionsChange_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Thing) {
          return mergeFrom((Thing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Thing other) {
        if (other == Thing.getDefaultInstance()) return this;
        if (other.hasStringId()) {
          setStringId(other.getStringId());
        }
        if (other.hasStringTypeName()) {
          setStringTypeName(other.getStringTypeName());
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000004);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        if (!other.connections_.isEmpty()) {
          if (connections_.isEmpty()) {
            connections_ = other.connections_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureConnectionsIsMutable();
            connections_.addAll(other.connections_);
          }
          onChanged();
        }
        if (other.hasConnectionsChange()) {
          setConnectionsChange(other.getConnectionsChange());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStringId()) {
          
          return false;
        }
        if (!hasStringTypeName()) {
          
          return false;
        }
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Thing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Thing) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 string_id = 1;
      private int stringId_ ;
      /**
       * <code>required int32 string_id = 1;</code>
       */
      public boolean hasStringId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 string_id = 1;</code>
       */
      public int getStringId() {
        return stringId_;
      }
      /**
       * <code>required int32 string_id = 1;</code>
       */
      public Builder setStringId(int value) {
        bitField0_ |= 0x00000001;
        stringId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 string_id = 1;</code>
       */
      public Builder clearStringId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringId_ = 0;
        onChanged();
        return this;
      }

      // required int32 string_type_name = 2;
      private int stringTypeName_ ;
      /**
       * <code>required int32 string_type_name = 2;</code>
       */
      public boolean hasStringTypeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 string_type_name = 2;</code>
       */
      public int getStringTypeName() {
        return stringTypeName_;
      }
      /**
       * <code>required int32 string_type_name = 2;</code>
       */
      public Builder setStringTypeName(int value) {
        bitField0_ |= 0x00000002;
        stringTypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 string_type_name = 2;</code>
       */
      public Builder clearStringTypeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stringTypeName_ = 0;
        onChanged();
        return this;
      }

      // repeated .ThingModel.Proto.Property properties = 3;
      private java.util.List<org.thingmodel.proto.ProtoProperty.Property> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          properties_ = new java.util.ArrayList<org.thingmodel.proto.ProtoProperty.Property>(properties_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.thingmodel.proto.ProtoProperty.Property, org.thingmodel.proto.ProtoProperty.Property.Builder, org.thingmodel.proto.ProtoProperty.PropertyOrBuilder> propertiesBuilder_;

      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public java.util.List<org.thingmodel.proto.ProtoProperty.Property> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoProperty.Property getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder setProperties(
          int index, org.thingmodel.proto.ProtoProperty.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder setProperties(
          int index, org.thingmodel.proto.ProtoProperty.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder addProperties(org.thingmodel.proto.ProtoProperty.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder addProperties(
          int index, org.thingmodel.proto.ProtoProperty.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder addProperties(
          org.thingmodel.proto.ProtoProperty.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder addProperties(
          int index, org.thingmodel.proto.ProtoProperty.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder addAllProperties(
          Iterable<? extends org.thingmodel.proto.ProtoProperty.Property> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          super.addAll(values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoProperty.Property.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoProperty.PropertyOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public java.util.List<? extends org.thingmodel.proto.ProtoProperty.PropertyOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoProperty.Property.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            org.thingmodel.proto.ProtoProperty.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoProperty.Property.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, org.thingmodel.proto.ProtoProperty.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.Property properties = 3;</code>
       */
      public java.util.List<org.thingmodel.proto.ProtoProperty.Property.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.thingmodel.proto.ProtoProperty.Property, org.thingmodel.proto.ProtoProperty.Property.Builder, org.thingmodel.proto.ProtoProperty.PropertyOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.thingmodel.proto.ProtoProperty.Property, org.thingmodel.proto.ProtoProperty.Property.Builder, org.thingmodel.proto.ProtoProperty.PropertyOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      // repeated int32 connections = 4 [packed = true];
      private java.util.List<Integer> connections_ = java.util.Collections.emptyList();
      private void ensureConnectionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          connections_ = new java.util.ArrayList<Integer>(connections_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public java.util.List<Integer>
          getConnectionsList() {
        return java.util.Collections.unmodifiableList(connections_);
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public int getConnectionsCount() {
        return connections_.size();
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public int getConnections(int index) {
        return connections_.get(index);
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public Builder setConnections(
          int index, int value) {
        ensureConnectionsIsMutable();
        connections_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public Builder addConnections(int value) {
        ensureConnectionsIsMutable();
        connections_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public Builder addAllConnections(
          Iterable<? extends Integer> values) {
        ensureConnectionsIsMutable();
        super.addAll(values, connections_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 connections = 4 [packed = true];</code>
       *
       * <pre>
       * Use int32 string ids
       * </pre>
       */
      public Builder clearConnections() {
        connections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // optional bool connections_change = 5 [default = false];
      private boolean connectionsChange_ ;
      /**
       * <code>optional bool connections_change = 5 [default = false];</code>
       */
      public boolean hasConnectionsChange() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool connections_change = 5 [default = false];</code>
       */
      public boolean getConnectionsChange() {
        return connectionsChange_;
      }
      /**
       * <code>optional bool connections_change = 5 [default = false];</code>
       */
      public Builder setConnectionsChange(boolean value) {
        bitField0_ |= 0x00000010;
        connectionsChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool connections_change = 5 [default = false];</code>
       */
      public Builder clearConnectionsChange() {
        bitField0_ = (bitField0_ & ~0x00000010);
        connectionsChange_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ThingModel.Proto.Thing)
    }

    static {
      defaultInstance = new Thing(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ThingModel.Proto.Thing)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_Thing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_Thing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Thing.proto\022\020ThingModel.Proto\032\016Propert" +
      "y.proto\"\240\001\n\005Thing\022\021\n\tstring_id\030\001 \002(\005\022\030\n\020" +
      "string_type_name\030\002 \002(\005\022.\n\nproperties\030\003 \003" +
      "(\0132\032.ThingModel.Proto.Property\022\027\n\013connec" +
      "tions\030\004 \003(\005B\002\020\001\022!\n\022connections_change\030\005 " +
      "\001(\010:\005falseB\"\n\024org.thingmodel.protoB\nProt" +
      "oThing"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ThingModel_Proto_Thing_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ThingModel_Proto_Thing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_Thing_descriptor,
              new String[] { "StringId", "StringTypeName", "Properties", "Connections", "ConnectionsChange", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.thingmodel.proto.ProtoProperty.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
