// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThingType.proto

package org.thingmodel.proto;

public final class ProtoThingType {
  private ProtoThingType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ThingTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 string_name = 1;
    /**
     * <code>required int32 string_name = 1;</code>
     */
    boolean hasStringName();
    /**
     * <code>required int32 string_name = 1;</code>
     */
    int getStringName();

    // optional int32 string_description = 2;
    /**
     * <code>optional int32 string_description = 2;</code>
     */
    boolean hasStringDescription();
    /**
     * <code>optional int32 string_description = 2;</code>
     */
    int getStringDescription();

    // repeated .ThingModel.Proto.PropertyType properties = 3;
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    java.util.List<org.thingmodel.proto.ProtoPropertyType.PropertyType> 
        getPropertiesList();
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    org.thingmodel.proto.ProtoPropertyType.PropertyType getProperties(int index);
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    java.util.List<? extends org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder> 
        getPropertiesOrBuilderList();
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder getPropertiesOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code ThingModel.Proto.ThingType}
   */
  public static final class ThingType extends
      com.google.protobuf.GeneratedMessage
      implements ThingTypeOrBuilder {
    // Use ThingType.newBuilder() to construct.
    private ThingType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ThingType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ThingType defaultInstance;
    public static ThingType getDefaultInstance() {
      return defaultInstance;
    }

    public ThingType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ThingType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stringName_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stringDescription_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                properties_ = new java.util.ArrayList<org.thingmodel.proto.ProtoPropertyType.PropertyType>();
                mutable_bitField0_ |= 0x00000004;
              }
              properties_.add(input.readMessage(org.thingmodel.proto.ProtoPropertyType.PropertyType.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoThingType.internal_static_ThingModel_Proto_ThingType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoThingType.internal_static_ThingModel_Proto_ThingType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ThingType.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ThingType> PARSER =
        new com.google.protobuf.AbstractParser<ThingType>() {
      public ThingType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThingType(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ThingType> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 string_name = 1;
    public static final int STRING_NAME_FIELD_NUMBER = 1;
    private int stringName_;
    /**
     * <code>required int32 string_name = 1;</code>
     */
    public boolean hasStringName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 string_name = 1;</code>
     */
    public int getStringName() {
      return stringName_;
    }

    // optional int32 string_description = 2;
    public static final int STRING_DESCRIPTION_FIELD_NUMBER = 2;
    private int stringDescription_;
    /**
     * <code>optional int32 string_description = 2;</code>
     */
    public boolean hasStringDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 string_description = 2;</code>
     */
    public int getStringDescription() {
      return stringDescription_;
    }

    // repeated .ThingModel.Proto.PropertyType properties = 3;
    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private java.util.List<org.thingmodel.proto.ProtoPropertyType.PropertyType> properties_;
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    public java.util.List<org.thingmodel.proto.ProtoPropertyType.PropertyType> getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    public java.util.List<? extends org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    public org.thingmodel.proto.ProtoPropertyType.PropertyType getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
     */
    public org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }

    private void initFields() {
      stringName_ = 0;
      stringDescription_ = 0;
      properties_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStringName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropertiesCount(); i++) {
        if (!getProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stringName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stringDescription_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(3, properties_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stringName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stringDescription_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, properties_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ThingType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ThingType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ThingType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ThingType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ThingType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ThingType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ThingType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ThingType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ThingType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ThingType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ThingType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThingModel.Proto.ThingType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ThingTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoThingType.internal_static_ThingModel_Proto_ThingType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoThingType.internal_static_ThingModel_Proto_ThingType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ThingType.class, Builder.class);
      }

      // Construct using org.thingmodel.proto.ProtoThingType.ThingType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stringName_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        stringDescription_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoThingType.internal_static_ThingModel_Proto_ThingType_descriptor;
      }

      public ThingType getDefaultInstanceForType() {
        return ThingType.getDefaultInstance();
      }

      public ThingType build() {
        ThingType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ThingType buildPartial() {
        ThingType result = new ThingType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringName_ = stringName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stringDescription_ = stringDescription_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ThingType) {
          return mergeFrom((ThingType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ThingType other) {
        if (other == ThingType.getDefaultInstance()) return this;
        if (other.hasStringName()) {
          setStringName(other.getStringName());
        }
        if (other.hasStringDescription()) {
          setStringDescription(other.getStringDescription());
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000004);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStringName()) {
          
          return false;
        }
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ThingType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ThingType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 string_name = 1;
      private int stringName_ ;
      /**
       * <code>required int32 string_name = 1;</code>
       */
      public boolean hasStringName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 string_name = 1;</code>
       */
      public int getStringName() {
        return stringName_;
      }
      /**
       * <code>required int32 string_name = 1;</code>
       */
      public Builder setStringName(int value) {
        bitField0_ |= 0x00000001;
        stringName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 string_name = 1;</code>
       */
      public Builder clearStringName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringName_ = 0;
        onChanged();
        return this;
      }

      // optional int32 string_description = 2;
      private int stringDescription_ ;
      /**
       * <code>optional int32 string_description = 2;</code>
       */
      public boolean hasStringDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 string_description = 2;</code>
       */
      public int getStringDescription() {
        return stringDescription_;
      }
      /**
       * <code>optional int32 string_description = 2;</code>
       */
      public Builder setStringDescription(int value) {
        bitField0_ |= 0x00000002;
        stringDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 string_description = 2;</code>
       */
      public Builder clearStringDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stringDescription_ = 0;
        onChanged();
        return this;
      }

      // repeated .ThingModel.Proto.PropertyType properties = 3;
      private java.util.List<org.thingmodel.proto.ProtoPropertyType.PropertyType> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          properties_ = new java.util.ArrayList<org.thingmodel.proto.ProtoPropertyType.PropertyType>(properties_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.thingmodel.proto.ProtoPropertyType.PropertyType, org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder, org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder> propertiesBuilder_;

      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public java.util.List<org.thingmodel.proto.ProtoPropertyType.PropertyType> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoPropertyType.PropertyType getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder setProperties(
          int index, org.thingmodel.proto.ProtoPropertyType.PropertyType value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder setProperties(
          int index, org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder addProperties(org.thingmodel.proto.ProtoPropertyType.PropertyType value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder addProperties(
          int index, org.thingmodel.proto.ProtoPropertyType.PropertyType value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder addProperties(
          org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder addProperties(
          int index, org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder addAllProperties(
          Iterable<? extends org.thingmodel.proto.ProtoPropertyType.PropertyType> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          super.addAll(values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public java.util.List<? extends org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            org.thingmodel.proto.ProtoPropertyType.PropertyType.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, org.thingmodel.proto.ProtoPropertyType.PropertyType.getDefaultInstance());
      }
      /**
       * <code>repeated .ThingModel.Proto.PropertyType properties = 3;</code>
       */
      public java.util.List<org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.thingmodel.proto.ProtoPropertyType.PropertyType, org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder, org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.thingmodel.proto.ProtoPropertyType.PropertyType, org.thingmodel.proto.ProtoPropertyType.PropertyType.Builder, org.thingmodel.proto.ProtoPropertyType.PropertyTypeOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ThingModel.Proto.ThingType)
    }

    static {
      defaultInstance = new ThingType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ThingModel.Proto.ThingType)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_ThingType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_ThingType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017ThingType.proto\022\020ThingModel.Proto\032\022Pro" +
      "pertyType.proto\"p\n\tThingType\022\023\n\013string_n" +
      "ame\030\001 \002(\005\022\032\n\022string_description\030\002 \001(\005\0222\n" +
      "\nproperties\030\003 \003(\0132\036.ThingModel.Proto.Pro" +
      "pertyTypeB&\n\024org.thingmodel.protoB\016Proto" +
      "ThingType"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ThingModel_Proto_ThingType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ThingModel_Proto_ThingType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_ThingType_descriptor,
              new String[] { "StringName", "StringDescription", "Properties", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.thingmodel.proto.ProtoPropertyType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
