// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PropertyType.proto

package org.thingmodel.proto;

public final class ProtoPropertyType {
  private ProtoPropertyType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PropertyTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 string_key = 1;
    /**
     * <code>required int32 string_key = 1;</code>
     */
    boolean hasStringKey();
    /**
     * <code>required int32 string_key = 1;</code>
     */
    int getStringKey();

    // required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];
    /**
     * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
     */
    boolean hasType();
    /**
     * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
     */
    PropertyType.Type getType();

    // required bool required = 3 [default = true];
    /**
     * <code>required bool required = 3 [default = true];</code>
     */
    boolean hasRequired();
    /**
     * <code>required bool required = 3 [default = true];</code>
     */
    boolean getRequired();

    // optional int32 string_name = 4;
    /**
     * <code>optional int32 string_name = 4;</code>
     */
    boolean hasStringName();
    /**
     * <code>optional int32 string_name = 4;</code>
     */
    int getStringName();

    // optional int32 string_description = 5;
    /**
     * <code>optional int32 string_description = 5;</code>
     */
    boolean hasStringDescription();
    /**
     * <code>optional int32 string_description = 5;</code>
     */
    int getStringDescription();
  }
  /**
   * Protobuf type {@code ThingModel.Proto.PropertyType}
   */
  public static final class PropertyType extends
      com.google.protobuf.GeneratedMessage
      implements PropertyTypeOrBuilder {
    // Use PropertyType.newBuilder() to construct.
    private PropertyType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PropertyType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PropertyType defaultInstance;
    public static PropertyType getDefaultInstance() {
      return defaultInstance;
    }

    public PropertyType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PropertyType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stringKey_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              Type value = Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              required_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              stringName_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              stringDescription_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoPropertyType.internal_static_ThingModel_Proto_PropertyType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoPropertyType.internal_static_ThingModel_Proto_PropertyType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PropertyType.class, Builder.class);
    }

    public static com.google.protobuf.Parser<PropertyType> PARSER =
        new com.google.protobuf.AbstractParser<PropertyType>() {
      public PropertyType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PropertyType(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PropertyType> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ThingModel.Proto.PropertyType.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOCATION = 0;</code>
       */
      LOCATION(0, 0),
      /**
       * <code>STRING = 1;</code>
       */
      STRING(1, 1),
      /**
       * <code>DOUBLE = 2;</code>
       */
      DOUBLE(2, 2),
      /**
       * <code>INT = 3;</code>
       */
      INT(3, 3),
      /**
       * <code>BOOLEAN = 4;</code>
       */
      BOOLEAN(4, 4),
      /**
       * <code>DATETIME = 5;</code>
       */
      DATETIME(5, 5),
      ;

      /**
       * <code>LOCATION = 0;</code>
       */
      public static final int LOCATION_VALUE = 0;
      /**
       * <code>STRING = 1;</code>
       */
      public static final int STRING_VALUE = 1;
      /**
       * <code>DOUBLE = 2;</code>
       */
      public static final int DOUBLE_VALUE = 2;
      /**
       * <code>INT = 3;</code>
       */
      public static final int INT_VALUE = 3;
      /**
       * <code>BOOLEAN = 4;</code>
       */
      public static final int BOOLEAN_VALUE = 4;
      /**
       * <code>DATETIME = 5;</code>
       */
      public static final int DATETIME_VALUE = 5;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return LOCATION;
          case 1: return STRING;
          case 2: return DOUBLE;
          case 3: return INT;
          case 4: return BOOLEAN;
          case 5: return DATETIME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PropertyType.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ThingModel.Proto.PropertyType.Type)
    }

    private int bitField0_;
    // required int32 string_key = 1;
    public static final int STRING_KEY_FIELD_NUMBER = 1;
    private int stringKey_;
    /**
     * <code>required int32 string_key = 1;</code>
     */
    public boolean hasStringKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 string_key = 1;</code>
     */
    public int getStringKey() {
      return stringKey_;
    }

    // required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];
    public static final int TYPE_FIELD_NUMBER = 2;
    private Type type_;
    /**
     * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
     */
    public Type getType() {
      return type_;
    }

    // required bool required = 3 [default = true];
    public static final int REQUIRED_FIELD_NUMBER = 3;
    private boolean required_;
    /**
     * <code>required bool required = 3 [default = true];</code>
     */
    public boolean hasRequired() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool required = 3 [default = true];</code>
     */
    public boolean getRequired() {
      return required_;
    }

    // optional int32 string_name = 4;
    public static final int STRING_NAME_FIELD_NUMBER = 4;
    private int stringName_;
    /**
     * <code>optional int32 string_name = 4;</code>
     */
    public boolean hasStringName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 string_name = 4;</code>
     */
    public int getStringName() {
      return stringName_;
    }

    // optional int32 string_description = 5;
    public static final int STRING_DESCRIPTION_FIELD_NUMBER = 5;
    private int stringDescription_;
    /**
     * <code>optional int32 string_description = 5;</code>
     */
    public boolean hasStringDescription() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 string_description = 5;</code>
     */
    public int getStringDescription() {
      return stringDescription_;
    }

    private void initFields() {
      stringKey_ = 0;
      type_ = Type.STRING;
      required_ = true;
      stringName_ = 0;
      stringDescription_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStringKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequired()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stringKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, required_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, stringName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, stringDescription_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stringKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, required_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, stringName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, stringDescription_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PropertyType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PropertyType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PropertyType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PropertyType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PropertyType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PropertyType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PropertyType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PropertyType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PropertyType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PropertyType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PropertyType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThingModel.Proto.PropertyType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PropertyTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoPropertyType.internal_static_ThingModel_Proto_PropertyType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoPropertyType.internal_static_ThingModel_Proto_PropertyType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PropertyType.class, Builder.class);
      }

      // Construct using org.thingmodel.proto.ProtoPropertyType.PropertyType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stringKey_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = Type.STRING;
        bitField0_ = (bitField0_ & ~0x00000002);
        required_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        stringName_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        stringDescription_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoPropertyType.internal_static_ThingModel_Proto_PropertyType_descriptor;
      }

      public PropertyType getDefaultInstanceForType() {
        return PropertyType.getDefaultInstance();
      }

      public PropertyType build() {
        PropertyType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PropertyType buildPartial() {
        PropertyType result = new PropertyType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringKey_ = stringKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.required_ = required_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.stringName_ = stringName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.stringDescription_ = stringDescription_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PropertyType) {
          return mergeFrom((PropertyType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PropertyType other) {
        if (other == PropertyType.getDefaultInstance()) return this;
        if (other.hasStringKey()) {
          setStringKey(other.getStringKey());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRequired()) {
          setRequired(other.getRequired());
        }
        if (other.hasStringName()) {
          setStringName(other.getStringName());
        }
        if (other.hasStringDescription()) {
          setStringDescription(other.getStringDescription());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStringKey()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasRequired()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PropertyType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PropertyType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 string_key = 1;
      private int stringKey_ ;
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public boolean hasStringKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public int getStringKey() {
        return stringKey_;
      }
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public Builder setStringKey(int value) {
        bitField0_ |= 0x00000001;
        stringKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 string_key = 1;</code>
       */
      public Builder clearStringKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringKey_ = 0;
        onChanged();
        return this;
      }

      // required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];
      private Type type_ = Type.STRING;
      /**
       * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
       */
      public Type getType() {
        return type_;
      }
      /**
       * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ThingModel.Proto.PropertyType.Type type = 2 [default = STRING];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = Type.STRING;
        onChanged();
        return this;
      }

      // required bool required = 3 [default = true];
      private boolean required_ = true;
      /**
       * <code>required bool required = 3 [default = true];</code>
       */
      public boolean hasRequired() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool required = 3 [default = true];</code>
       */
      public boolean getRequired() {
        return required_;
      }
      /**
       * <code>required bool required = 3 [default = true];</code>
       */
      public Builder setRequired(boolean value) {
        bitField0_ |= 0x00000004;
        required_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool required = 3 [default = true];</code>
       */
      public Builder clearRequired() {
        bitField0_ = (bitField0_ & ~0x00000004);
        required_ = true;
        onChanged();
        return this;
      }

      // optional int32 string_name = 4;
      private int stringName_ ;
      /**
       * <code>optional int32 string_name = 4;</code>
       */
      public boolean hasStringName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 string_name = 4;</code>
       */
      public int getStringName() {
        return stringName_;
      }
      /**
       * <code>optional int32 string_name = 4;</code>
       */
      public Builder setStringName(int value) {
        bitField0_ |= 0x00000008;
        stringName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 string_name = 4;</code>
       */
      public Builder clearStringName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        stringName_ = 0;
        onChanged();
        return this;
      }

      // optional int32 string_description = 5;
      private int stringDescription_ ;
      /**
       * <code>optional int32 string_description = 5;</code>
       */
      public boolean hasStringDescription() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 string_description = 5;</code>
       */
      public int getStringDescription() {
        return stringDescription_;
      }
      /**
       * <code>optional int32 string_description = 5;</code>
       */
      public Builder setStringDescription(int value) {
        bitField0_ |= 0x00000010;
        stringDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 string_description = 5;</code>
       */
      public Builder clearStringDescription() {
        bitField0_ = (bitField0_ & ~0x00000010);
        stringDescription_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ThingModel.Proto.PropertyType)
    }

    static {
      defaultInstance = new PropertyType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ThingModel.Proto.PropertyType)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ThingModel_Proto_PropertyType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ThingModel_Proto_PropertyType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022PropertyType.proto\022\020ThingModel.Proto\"\370" +
      "\001\n\014PropertyType\022\022\n\nstring_key\030\001 \002(\005\0229\n\004t" +
      "ype\030\002 \002(\0162#.ThingModel.Proto.PropertyTyp" +
      "e.Type:\006STRING\022\026\n\010required\030\003 \002(\010:\004true\022\023" +
      "\n\013string_name\030\004 \001(\005\022\032\n\022string_descriptio" +
      "n\030\005 \001(\005\"P\n\004Type\022\014\n\010LOCATION\020\000\022\n\n\006STRING\020" +
      "\001\022\n\n\006DOUBLE\020\002\022\007\n\003INT\020\003\022\013\n\007BOOLEAN\020\004\022\014\n\010D" +
      "ATETIME\020\005B)\n\024org.thingmodel.protoB\021Proto" +
      "PropertyType"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ThingModel_Proto_PropertyType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ThingModel_Proto_PropertyType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ThingModel_Proto_PropertyType_descriptor,
              new String[] { "StringKey", "Type", "Required", "StringName", "StringDescription", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
