//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Property.proto
namespace ThingModel.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Property")]
  public partial class Property : global::ProtoBuf.IExtensible
  {
    public Property() {}
    
    private int _string_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"string_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int string_key
    {
      get { return _string_key; }
      set { _string_key = value; }
    }
    private ThingModel.Proto.Property.Location _location = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ThingModel.Proto.Property.Location location
    {
      get { return _location; }
      set { _location = value; }
    }
    private ThingModel.Proto.Property.String _string = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ThingModel.Proto.Property.String @string
    {
      get { return _string; }
      set { _string = value; }
    }
    private ThingModel.Proto.Property.Double _double = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"double", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ThingModel.Proto.Property.Double @double
    {
      get { return _double; }
      set { _double = value; }
    }
    private ThingModel.Proto.Property.Int _int = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"int", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ThingModel.Proto.Property.Int @int
    {
      get { return _int; }
      set { _int = value; }
    }
    private ThingModel.Proto.Property.Boolean _boolean = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"boolean", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ThingModel.Proto.Property.Boolean boolean
    {
      get { return _boolean; }
      set { _boolean = value; }
    }
    private ThingModel.Proto.Property.DateTime _datetime = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"datetime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ThingModel.Proto.Property.DateTime datetime
    {
      get { return _datetime; }
      set { _datetime = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Location")]
  public partial class Location : global::ProtoBuf.IExtensible
  {
    public Location() {}
    
    private double _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double x
    {
      get { return _x; }
      set { _x = value; }
    }
    private double _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double y
    {
      get { return _y; }
      set { _y = value; }
    }
    private double _z = (double)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((double)0)]
    public double z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _string_system = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"string_system", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int string_system
    {
      get { return _string_system; }
      set { _string_system = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"String")]
  public partial class String : global::ProtoBuf.IExtensible
  {
    public String() {}
    
    private string _value = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private string _value_key = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string value_key
    {
      get { return _value_key; }
      set { _value_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Double")]
  public partial class Double : global::ProtoBuf.IExtensible
  {
    public Double() {}
    
    private double _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Int")]
  public partial class Int : global::ProtoBuf.IExtensible
  {
    public Int() {}
    
    private int _Value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Boolean")]
  public partial class Boolean : global::ProtoBuf.IExtensible
  {
    public Boolean() {}
    
    private bool _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DateTime")]
  public partial class DateTime : global::ProtoBuf.IExtensible
  {
    public DateTime() {}
    
    private int _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}