//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ThingType.proto
// Note: requires additional types generated from: PropertyType.proto
namespace ThingModel.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ThingType")]
  public partial class ThingType : global::ProtoBuf.IExtensible
  {
    public ThingType() {}
    
    private int _string_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"string_name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int string_name
    {
      get { return _string_name; }
      set { _string_name = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private readonly global::System.Collections.Generic.List<ThingModel.Proto.PropertyType> _properties = new global::System.Collections.Generic.List<ThingModel.Proto.PropertyType>();
    [global::ProtoBuf.ProtoMember(3, Name=@"properties", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ThingModel.Proto.PropertyType> properties
    {
      get { return _properties; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}